# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'airchecknasa' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for airchecknasa
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'

  target 'airchecknasaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'airchecknasaUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
